name: selfcheckcovid19
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  google_fonts: ^0.3.10
  rflutter_alert: ^1.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
flutter_icons:
  ios: true
  android: true
  image_path: "assets/launcher/icon.png"
#  image_path_ios: "assets/launcher/icon.png"
#  image_path_android: "assets/launcher/icon.png"
#  adaptive_icon_background: "assets/launcher/background.png"
#  adaptive_icon_foreground: "assets/launcher/foreground.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
